# __ELT__

We import the libraries and create the dataframes.

In [25]:
import pandas as pd
import numpy as np

In [26]:
# The 4 csv are imported for create the dataframes

netflix=pd.read_csv("Datasets/amazon_prime_titles.csv")
hulu=pd.read_csv("Datasets/hulu_titles.csv")
disney_plus=pd.read_csv("Datasets/disney_plus_titles.csv")
amazon_prime=pd.read_csv("Datasets/amazon_prime_titles.csv")

In [27]:
netflix.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...

In [28]:
hulu.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Ricky Velez: Here's Everything,NaN,NaN,NaN,"October 24, 2021",2021,TV-MA,NaN,"Comedy, Stand Up",​Comedian Ricky Velez bares it all with his ho...
1,s2,Movie,Silent Night,NaN,NaN,NaN,"October 23, 2021",2020,NaN,94 min,"Crime, Drama, Thriller","Mark, a low end South London hitman recently r..."
2,s3,Movie,The Marksman,NaN,NaN,NaN,"October 23, 2021",2021,PG-13,108 min,"Action, Thriller",A hardened Arizona rancher tries to protect an...

In [29]:
disney_plus.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.

In [30]:
amazon_prime.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...

. Create the __id__ field in each dataframe, which is composed of the first letter of the platform name  
. Create __platform__ field to have a better follow-up of which platform the row belongs to

In [31]:
#'id' field 
amazon_prime.insert(0,"id", ("a"+amazon_prime["show_id"]))

disney_plus.insert(0,"id", ("d"+disney_plus["show_id"]))

hulu.insert(0,"id", ("h"+hulu["show_id"]))

netflix.insert(0,"id", ("n"+amazon_prime["show_id"]))

In [32]:
#'platform' field
amazon_prime['platform']='amazonPrime'; disney_plus['platform']='disney'; netflix['platform']='netflix'; hulu['platform']='hulu'

.Now we concatenate all in a single dataframe using __concat()__ and reset the index.

In [33]:
DF_Proyect = pd.concat([amazon_prime, netflix, disney_plus, hulu], axis=0)

In [34]:
DF_Proyect.reset_index(drop=True, inplace=True)

In [35]:
DF_Proyect.sample(5)

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,platform
503,as504,s504,TV Show,The Office,NaN,"Lucy Davis, Ricky Gervais, Martin Freeman, Mac...",NaN,NaN,2003,TV-14,2 Seasons,Comedy,Season 2 of the multi-award winning comedy set...,amazonPrime
17049,ns7382,s7382,Movie,Sharyat,Viju Mane,"Sachin Pilgaonkar, Santosh Juvekar, Tejashree ...",NaN,NaN,2011,ALL,126 min,"Action, Drama","Dhananjay (Sachin Pilgaonkar), an ace bullock ...",netflix
15331,ns5664,s5664,Movie,Borat Subsequent Moviefilm,Jason Woliner,"Sacha Baron Cohen, Maria Bakalova","United Kingdom, United States",NaN,2020,R,96 min,Comedy,Delivery of Prodigious Bribe to American Regim...,netflix
21691,hs906,s906,TV Show,Absolutely Ascot,NaN,NaN,NaN,"March 9, 2021",2018,NaN,2 Seasons,Reality,"Big characters, extravagant lifestyles, tumult...",hulu
7374,as7375,s7375,Movie,The Object of Beauty,Michael Lindsay-Hogg,"John Malkovich, Andie McDowell, Joss Ackland, ...",NaN,NaN,1991,R,103 min,"Comedy, Drama",Jake (John Malkovich) and Tina (Andie MacDowel...,amazonPrime

In [36]:
# Columns datatypes
DF_Proyect.dtypes

id              object
show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
platform        object
dtype: object

In [37]:
print("Dataset size: ",DF_Proyect.shape," and the duplicated data: ", DF_Proyect.duplicated().sum())

Dataset size:  (23859, 14)  and the duplicated data:  0

In [38]:
#Number of nulls in columns

DF_Proyect.isnull().sum().sort_values()

id                  0
show_id             0
type                0
title               0
release_year        0
listed_in           0
platform            0
description         4
duration          479
rating           1197
cast             5729
director         7707
date_added      19057
country         19664
dtype: int64

.We replace the null values with __'G'__ in the rating field (maturity rating: “general for all audiences”)  
.Change to __lowercase__ all the fields content

In [39]:
DF_Proyect.rating.fillna('g', inplace=True)

In [40]:
#All the strings in the dataframe to lowercase

DF_Proyect['type'] = DF_Proyect['type'].str.lower()
DF_Proyect['title'] = DF_Proyect['title'].str.lower()
DF_Proyect['director'] = DF_Proyect['director'].str.lower()
DF_Proyect['cast'] = DF_Proyect['cast'].str.lower()
DF_Proyect['country'] = DF_Proyect['country'].str.lower()
DF_Proyect['date_added'] = DF_Proyect['date_added'].str.lower()
DF_Proyect['rating'] = DF_Proyect['rating'].str.lower()
DF_Proyect['listed_in'] = DF_Proyect['listed_in'].str.lower()
DF_Proyect['description'] = DF_Proyect['description'].str.lower()
DF_Proyect['platform'] = DF_Proyect['platform'].str.lower()

.Duration --> __Duration_type__, __Duration_int__  

.We __convert__ the __date_added__ field to __datetime(Y/m/d)__

In [41]:
#Convert all the elements of duration in str, now we split in two duration, duration_int(integer) and duration_type(string)
DF_Proyect['duration']=DF_Proyect['duration'].astype(str)

DF_Proyect['duration_int']= DF_Proyect['duration'].apply(lambda x:x.split()[0])
DF_Proyect['duration_type']=DF_Proyect['duration'].apply(lambda x:str(x.split()[1:]))


#Remove duration column
DF_Proyect=DF_Proyect.drop(['duration'], axis=1)

In [45]:
#Now we convert to datetime "date_added" and we change to the format YYYY-MM-DD
DF_Proyect["date_added"] = pd.to_datetime(DF_Proyect['date_added'], errors='coerce')
DF_Proyect['date_added'] = DF_Proyect['date_added'].dt.strftime("%Y-%m-%d")