# __ETL__
MVP

We import the libraries and create the dataframes.

In [70]:
import pandas as pd
import numpy as np

In [133]:
# The 4 csv are imported for create the dataframes

netflix=pd.read_csv("Datasets/amazon_prime_titles.csv")
hulu=pd.read_csv("Datasets/hulu_titles.csv")
disney_plus=pd.read_csv("Datasets/disney_plus_titles.csv")
amazon_prime=pd.read_csv("Datasets/amazon_prime_titles.csv")

In [98]:
netflix.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...

In [73]:
hulu.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Ricky Velez: Here's Everything,NaN,NaN,NaN,"October 24, 2021",2021,TV-MA,NaN,"Comedy, Stand Up",​Comedian Ricky Velez bares it all with his ho...
1,s2,Movie,Silent Night,NaN,NaN,NaN,"October 23, 2021",2020,NaN,94 min,"Crime, Drama, Thriller","Mark, a low end South London hitman recently r..."
2,s3,Movie,The Marksman,NaN,NaN,NaN,"October 23, 2021",2021,PG-13,108 min,"Action, Thriller",A hardened Arizona rancher tries to protect an...

In [74]:
disney_plus.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.

In [75]:
amazon_prime.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...

. Create the __id__ field in each dataframe, which is composed of the first letter of the platform name  
. Create __platform__ field to have a better follow-up of which platform the row belongs to

In [134]:
#'id' field 
amazon_prime.insert(0,"id", ("a"+amazon_prime["show_id"]))

disney_plus.insert(0,"id", ("d"+disney_plus["show_id"]))

hulu.insert(0,"id", ("h"+hulu["show_id"]))

netflix.insert(0,"id", ("n"+amazon_prime["show_id"]))

In [135]:
#'platform' field
amazon_prime['platform']='amazonPrime'; disney_plus['platform']='disney'; netflix['platform']='netflix'; hulu['platform']='hulu'

.Now we concatenate all in a single dataframe using __concat()__ and reset the index.

In [136]:
DF_Proyect = pd.concat([amazon_prime, netflix, disney_plus, hulu], axis=0)

In [138]:
DF_Proyect.reset_index(drop=True, inplace=True)

In [139]:
DF_Proyect.sample(5)

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,platform
2813,as2814,s2814,Movie,Code Of The Red Man,Edward Finney,"Ted Adams, Chief Thurndercloud, Rick Vallin, D...",NaN,NaN,1942,18+,66 min,Western,"Nakoma, a wild stallion, threatens any animal ...",amazonPrime
13088,ns3421,s3421,TV Show,A French Village (English subtitled),NaN,"Thierry Godard, Robin Renucci, Audrey Fleurot,...",NaN,NaN,2013,16+,3 Seasons,TV Shows,In French with English subtitles. This acclaim...,netflix
16561,ns6894,s6894,Movie,Andy Peters: Question. Point. Exclamation Mark.,Steven Feinartz,Andy Peters,NaN,NaN,2015,18+,49 min,"Arts, Entertainment, and Culture, Comedy, Spec...","Filmed at The Virgil in Los Angeles, Andy Pete...",netflix
8656,as8657,s8657,Movie,Sex and Chocolate,Gavin Millar,"Dawn French, Phil Daniels, Michael Maloney",NaN,NaN,1997,16+,87 min,"Drama, Romance","Bev, a warm and cuddly wife and mum who is hap...",amazonPrime
20031,ds696,s696,TV Show,Miles From Tomorrowland,NaN,"Olivia Munn, Cullen McCarthy, Fiona Bishop, De...",United States,"December 1, 2019",2014,TV-Y,2 Seasons,"Action-Adventure, Animation, Kids",Blastastic! Join Miles and his family in outer...,disney

In [36]:
# Columns datatypes
DF_Proyect.dtypes

id              object
show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
platform        object
dtype: object

In [140]:
print("Dataset size: ",DF_Proyect.shape," and the duplicated data: ", DF_Proyect.duplicated().sum())

Dataset size:  (23859, 14)  and the duplicated data:  0

In [121]:
#Number of nulls in columns

DF_Proyect.isnull().sum().sort_values()

id                  0
show_id             0
type                0
title               0
release_year        0
listed_in           0
platform            0
description         4
duration          479
rating           1197
cast             5729
director         7707
date_added      19057
country         19664
dtype: int64

.We replace the null values with __'G'__ in the rating field (maturity rating: “general for all audiences”)  
.Change to __lowercase__ all the fields content

In [141]:
DF_Proyect.rating.fillna('g', inplace=True)

In [142]:
#All the strings in the dataframe to lowercase

DF_Proyect['type'] = DF_Proyect['type'].str.lower()
DF_Proyect['title'] = DF_Proyect['title'].str.lower()
DF_Proyect['director'] = DF_Proyect['director'].str.lower()
DF_Proyect['cast'] = DF_Proyect['cast'].str.lower()
DF_Proyect['country'] = DF_Proyect['country'].str.lower()
DF_Proyect['date_added'] = DF_Proyect['date_added'].str.lower()
DF_Proyect['rating'] = DF_Proyect['rating'].str.lower()
DF_Proyect['listed_in'] = DF_Proyect['listed_in'].str.lower()
DF_Proyect['description'] = DF_Proyect['description'].str.lower()
DF_Proyect['platform'] = DF_Proyect['platform'].str.lower()

.Duration --> __Duration_type__, __Duration_int__  

.We __convert__ the __date_added__ field to __datetime(Y/m/d)__

In [143]:
#Convert all the elements of duration in str, now we split in two duration, duration_int(integer) and duration_type(string)
DF_Proyect['duration']=DF_Proyect['duration'].astype(str)

DF_Proyect['duration_int']= DF_Proyect['duration'].apply(lambda x:x.split()[0])
DF_Proyect['duration_type']=DF_Proyect['duration'].apply(lambda x:str(x.split()[1:]))


#Remove duration column
DF_Proyect=DF_Proyect.drop(['duration'], axis=1)

In [144]:
#Now we convert to datetime "date_added" and we change to the format YYYY-MM-DD
DF_Proyect["date_added"] = pd.to_datetime(DF_Proyect['date_added'], errors='coerce')
DF_Proyect['date_added'] = DF_Proyect['date_added'].dt.strftime("%Y-%m-%d")

In [55]:
#DF_Proyect.to_csv("Datasets/DF_MoviesAndSeries.csv",index=False)

In [129]:
DF_Proyect

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,platform,duration_int,duration_type
0,as1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,"comedy, drama",a small fishing village must procure a local d...,amazonprime,113,['min']
1,as2,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,"drama, international",a metro family decides to fight a cyber crimin...,amazonprime,110,['min']
2,as3,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,"action, drama, suspense",after a man discovers his wife is cheating on ...,amazonprime,74,['min']
3,as4,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,g,documentary,"pink breaks the mold once again, bringing her ...",amazonprime,69,['min']
4,as5,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,"drama, fantasy",teenage matt banting wants to work with a famo...,amazonprime,45,['min']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23854,hs3069,s3069,tv show,star trek: the original series,NaN,NaN,united states,NaN,1966,tv-pg,"action, adventure, classics",the 23rd century adventures of captain james t...,hulu,3,['Seasons']
23855,hs3070,s3070,tv show,star trek: voyager,NaN,NaN,united states,NaN,1997,tv-pg,"action, adventure, science fiction",catapulted into the distant sector of the gala...,hulu,7,['Seasons']
23856,hs3071,s3071,tv show,the fades,NaN,NaN,united kingdom,NaN,2011,tv-14,"horror, international, science fiction",seventeen-year-old paul is haunted by apocalyp...,hulu,1,['Season']
23857,hs3072,s3072,tv show,the twilight zone,NaN,NaN,united states,NaN,1959,tv-pg,"classics, science fiction, thriller",rod serling's seminal anthology series focused...,hulu,5,['Seasons']
23858,hs3073,s3073,tv show,tokyo magnitude 8.0,NaN,NaN,japan,NaN,2009,tv-14,"anime, drama, international",the devastation is unleashed in the span of se...,hulu,1,['Season']